[modules.LogicBusiness]
output = "Modules/logic-business/Tests/Mock/GeneratedMocks.swift"
testableImports = ["logic_business"]
sources = [
    "Modules/logic-business/Sources/**/*.swift"
]

[modules.LogicBusiness.options]
glob = true
keepDocumentation = false
enableInheritance = true
protocolsOnly = true
omitHeaders = false

[modules.LogicApi]
output = "Modules/logic-api/Tests/Mock/GeneratedMocks.swift"
testableImports = [
	"logic_core", 
	"logic_business", 
	"logic_analytics",
	"logic_api"
]
sources = [
	"Modules/logic-core/Sources/**/*.swift",
	"Modules/logic-business/Sources/**/*.swift",
	"Modules/logic-analytics/Sources/**/*.swift",
    "Modules/logic-api/Sources/**/*.swift"
]

[modules.LogicApi.options]
glob = true
keepDocumentation = false
enableInheritance = true
protocolsOnly = true
omitHeaders = false

[modules.LogicUi]
output = "Modules/logic-ui/Tests/Mock/GeneratedMocks.swift"
testableImports = [
	"logic_core", 
	"logic_business", 
	"logic_analytics",
	"logic_ui"
]
sources = [
	"Modules/logic-core/Sources/**/*.swift",
	"Modules/logic-business/Sources/**/*.swift",
	"Modules/logic-analytics/Sources/**/*.swift",
    "Modules/logic-ui/Sources/**/*.swift"
]

[modules.LogicUi.options]
glob = true
keepDocumentation = false
enableInheritance = true
protocolsOnly = true
omitHeaders = false

[modules.LogicAuth]
output = "Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift"
testableImports = [
	"logic_core", 
	"logic_business", 
	"logic_analytics",
	"logic_authentication"
]
sources = [
	"Modules/logic-core/Sources/**/*.swift",
	"Modules/logic-business/Sources/**/*.swift",
	"Modules/logic-analytics/Sources/**/*.swift",
    "Modules/logic-authentication/Sources/**/*.swift"
]

[modules.LogicAuth.options]
glob = true
keepDocumentation = false
enableInheritance = true
protocolsOnly = true
omitHeaders = false

[modules.FeatureCommon]
output = "Modules/feature-common/Tests/Mock/GeneratedMocks.swift"
testableImports = [
	"logic_core", 
	"logic_business", 
	"logic_analytics",
	"logic_ui", 
	"logic_api", 
	"logic_authentication",
	"feature_common"
]
sources = [
	"Modules/logic-core/Sources/**/*.swift",
	"Modules/logic-business/Sources/**/*.swift",
	"Modules/logic-analytics/Sources/**/*.swift",
	"Modules/logic-ui/Sources/**/*.swift",
	"Modules/logic-api/Sources/**/*.swift",
	"Modules/logic-authentication/Sources/**/*.swift",
    "Modules/feature-common/Sources/**/*.swift"
]

[modules.FeatureCommon.options]
glob = true
keepDocumentation = false
enableInheritance = true
protocolsOnly = true
omitHeaders = false

[modules.FeatureDashboard]
output = "Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift"
testableImports = [
	"logic_core", 
	"logic_business", 
	"logic_analytics",
	"logic_ui", 
	"logic_api", 
	"logic_authentication",
	"feature_common",
	"feature_dashboard"
]
sources = [
	"Modules/logic-core/Sources/**/*.swift",
	"Modules/logic-business/Sources/**/*.swift",
	"Modules/logic-analytics/Sources/**/*.swift",
	"Modules/logic-ui/Sources/**/*.swift",
	"Modules/logic-api/Sources/**/*.swift",
	"Modules/logic-authentication/Sources/**/*.swift",
    "Modules/feature-common/Sources/**/*.swift",
    "Modules/feature-dashboard/Sources/**/*.swift"
]

[modules.FeatureDashboard.options]
glob = true
keepDocumentation = false
enableInheritance = true
protocolsOnly = true
omitHeaders = false

[modules.FeatureLogin]
output = "Modules/feature-login/Tests/Mock/GeneratedMocks.swift"
testableImports = [
	"logic_core", 
	"logic_business", 
	"logic_analytics",
	"logic_ui", 
	"logic_api", 
	"logic_authentication",
	"feature_common",
	"feature_login"
]
sources = [
	"Modules/logic-core/Sources/**/*.swift",
	"Modules/logic-business/Sources/**/*.swift",
	"Modules/logic-analytics/Sources/**/*.swift",
	"Modules/logic-ui/Sources/**/*.swift",
	"Modules/logic-api/Sources/**/*.swift",
	"Modules/logic-authentication/Sources/**/*.swift",
    "Modules/feature-common/Sources/**/*.swift",
    "Modules/feature-login/Sources/**/*.swift"
]

[modules.FeatureLogin.options]
glob = true
keepDocumentation = false
enableInheritance = true
protocolsOnly = true
omitHeaders = false

[modules.FeatureStartup]
output = "Modules/feature-startup/Tests/Mock/GeneratedMocks.swift"
testableImports = [
	"logic_core", 
	"logic_business", 
	"logic_analytics",
	"logic_ui", 
	"logic_api", 
	"logic_authentication",
	"feature_common",
	"feature_startup"
]
sources = [
	"Modules/logic-core/Sources/**/*.swift",
	"Modules/logic-business/Sources/**/*.swift",
	"Modules/logic-analytics/Sources/**/*.swift",
	"Modules/logic-ui/Sources/**/*.swift",
	"Modules/logic-api/Sources/**/*.swift",
	"Modules/logic-authentication/Sources/**/*.swift",
    "Modules/feature-common/Sources/**/*.swift",
    "Modules/feature-startup/Sources/**/*.swift"
]

[modules.FeatureStartup.options]
glob = true
keepDocumentation = false
enableInheritance = true
protocolsOnly = true
omitHeaders = false

[modules.FeaturePresentation]
output = "Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift"
testableImports = [
	"logic_core", 
	"logic_business", 
	"logic_analytics",
	"logic_ui", 
	"logic_api", 
	"logic_authentication",
	"feature_common",
	"feature_presentation"
]
sources = [
	"Modules/logic-core/Sources/**/*.swift",
	"Modules/logic-business/Sources/**/*.swift",
	"Modules/logic-analytics/Sources/**/*.swift",
	"Modules/logic-ui/Sources/**/*.swift",
	"Modules/logic-api/Sources/**/*.swift",
	"Modules/logic-authentication/Sources/**/*.swift",
    "Modules/feature-common/Sources/**/*.swift",
    "Modules/feature-presentation/Sources/**/*.swift"
]

[modules.FeaturePresentation.options]
glob = true
keepDocumentation = false
enableInheritance = true
protocolsOnly = true
omitHeaders = false

[modules.FeatureIssuance]
output = "Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift"
testableImports = [
	"logic_core", 
	"logic_business", 
	"logic_analytics",
	"logic_ui", 
	"logic_api", 
	"logic_authentication",
	"feature_common",
	"feature_issuance"
]
sources = [
	"Modules/logic-core/Sources/**/*.swift",
	"Modules/logic-business/Sources/**/*.swift",
	"Modules/logic-analytics/Sources/**/*.swift",
	"Modules/logic-ui/Sources/**/*.swift",
	"Modules/logic-api/Sources/**/*.swift",
	"Modules/logic-authentication/Sources/**/*.swift",
    "Modules/feature-common/Sources/**/*.swift",
    "Modules/feature-issuance/Sources/**/*.swift"
]

[modules.FeatureIssuance.options]
glob = true
keepDocumentation = false
enableInheritance = true
protocolsOnly = true
omitHeaders = false

[modules.FeatureProximity]
output = "Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift"
testableImports = [
	"logic_core", 
	"logic_business", 
	"logic_analytics",
	"logic_ui", 
	"logic_api", 
	"logic_authentication",
	"feature_common",
	"feature_proximity"
]
sources = [
	"Modules/logic-core/Sources/**/*.swift",
	"Modules/logic-business/Sources/**/*.swift",
	"Modules/logic-analytics/Sources/**/*.swift",
	"Modules/logic-ui/Sources/**/*.swift",
	"Modules/logic-api/Sources/**/*.swift",
	"Modules/logic-authentication/Sources/**/*.swift",
    "Modules/feature-common/Sources/**/*.swift",
    "Modules/feature-proximity/Sources/**/*.swift"
]

[modules.FeatureProximity.options]
glob = true
keepDocumentation = false
enableInheritance = true
protocolsOnly = true
omitHeaders = false