---
name: build-package
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: ['main']
    tags: [ v* ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.1'
      - uses: actions/checkout@v6
      - run:
          fastlane tests scheme: 'EUDI Wallet Dev'